fix: open options list on input focus [MDS-1378]
coingaming/moon-light pull request #219
Opened 2024-11-28 18:51 UTC by MarioGranada

2024-12-02 15:37 UTC, dkireev requested changes
In examples with Combobox.Select when no option is selected navigating with TAB sets the first option from the list. Should open dropdown and then blur out without selecting anything

2024-12-05 14:09 UTC, MarioGranada commented
Agreed. Just made a fix @dkireev , please have a look.

2024-12-10 15:33 UTC, robb91-dev approved these changes

2024-12-11 08:36 UTC, dkireev approved these changes

2024-12-11 08:36 UTC, merged